### ISSUE TITLE
Proposal for code indentation

### ISSUE THREAD

**Issue by cecton** [yaahc/indenter#10]
Hello :wave: 

I made another indenter but for a different use case: to indent code. This is useful when you want to output code in a `build.rs` script for example. Particularly if the code generated is in an different language than Rust.

I already made the formatter struct there: https://github.com/cecton/code-formatter

Before I make yet another crate on crates.io, I thought maybe it would be nice to join effort. The downside for you is that it increases the original scope of your project because it indents & dedents, and also the use case is different (`indenter`'s use case is to format error messages while this one is to format code).

Let me know if you want to join effort. If you accept, I will update the documentation accordingly to include the bigger scope of this crate.

**Comment by yaahc** [comment]
Hey @cecton :wave: :smile:,

I'd be happy to host code formatting logic in `indenter`, though depending on how much code that entails I may want it behind a feature flag and disabled by default.

**Comment by cecton** [comment]
I missed the opportunity to call you Director Jane! Sounds cool imo! 😁  It reminds me of GI Jane or "the Director" in Control (video game).

> depending on how much code that entails I may want it behind a feature flag and disabled by default.

I was hoping you could tell already, I added the repository to this issue expressly so you can see 😁

**Comment by yaahc** [comment]
> I was hoping you could tell already, I added the repository to this issue expressly so you can see 😁

Oh wow yea that looks totally fine, no feature flag needed

**Comment by cecton** [comment]
Ok thanks!! I will make a PR Soon :tm:

**Comment by regexident** [comment]
I needed exactly this (indenting another language's source code) a couple of days ago.
So I searched on crates.io, found this project, but realized it didn't quite match my requirements.

I can't wait to use this, once it lands! ☺️

**Comment by cecton** [comment]
omg you have no idea how happy I am to hear this. Thanks a lot for saying it!! @regexident

**Comment by yaahc** [comment]
closed by #11 and #12 :tada:
