### ISSUE TITLE
Support io::Write

### ISSUE THREAD

**Issue by lpil** [yaahc/indenter#3]
Hello!

I'm not sure I understand the split between `std::io` and `core::fmt` `Write`, but it seems to me that this library would be useful for both traits. The `io` trait seems more commonly used than `fmt`.

Does it seem within scope of this library?

Cheers,
Louis

**Comment by lpil** [comment]
Oh wait, `io::Write` can be any data at all, not just text. I feel like I've forgotten to put my thinking cap on this morning 😵

**Comment by yaahc** [comment]
:heart: lol, no worries

**Comment by lpil** [comment]
Thank!
